server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 120.24.204.157
    port: 5672
    username: admin
    password: 123
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          exvironment: #设置rabbitmq的相关的坏境配置
            spring:
              rabbitmq:
                host: 120.24.204.157
                port: 5672
                username: admin
                password: 123
      bindings: #服务器的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为奶son,文本则设置text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
#          group: example2
          group: example1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔（默认是90秒）
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认是30秒）
    instance-id: receive-8803.com #在信息列表时显式主机名称
    prefer-ip-address: true #访间的路径变为IP地址
