server:
  port: 84

spring:
  application:
    name: order84
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080


#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
  hystrix:
    enabled: false

serverUrl: http://provider-payment
