<template>
    <div>
        <h2>{{name}}</h2>
        <h2>{{name1}}</h2>
    </div>
</template>
<script>
    export default {
        name:Student,
        data(){
            return{
                name:'Vue',
                name1:'Good!'
            }
        }
    }
</script>
<style>
</style>