spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      aop-patterns: com.example.springbootdatajdbc.*
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  jdbc:
    template:
      query-timeout: 3
server:
  port: 8080